version: '3'
services:

  todo-nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - todo-php-fpm
    ports:
      - "8040:80"

  todo-php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-fpm.docker
    environment:
      PHP_IDE_CONFIG: "serverName=todolist-symfony.local"
    volumes:
      - ./:/app
    depends_on:
      - todo-postgres
      - mailer
      - todo-redis

  todo-php-cli:
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - todo-postgres
      - todo-redis
      - mailer

  todo-node-watch:
    image: node:14.15-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

  todo-node:
    image: node:14.15-alpine
    volumes:
      - ./:/app
    working_dir: /app

  todo-postgres:
    image: postgres:11.2-alpine
    volumes:
      - todo-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54322:5432"

  todo-redis:
    image: redis:3.0-alpine
    volumes:
      - todo-redis:/data
    command: redis-server --requirepass secret

  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"

volumes:
  todo-postgres:
  todo-redis:
  composer: