doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: -

        url: '%env(resolve:DATABASE_URL)%'

        types:
            user_id: 'App\Domain\Auth\User\Entity\User\Type\IdType'
            user_role: 'App\Domain\Auth\User\Entity\User\Type\RoleType'
            user_email: 'App\Domain\Auth\User\Entity\User\Type\EmailType'
            todos_task_id: 'App\Domain\Todos\Task\Entity\Task\Type\IdType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Auth/User/Entity'
                prefix: 'App\Domain\Auth\User\Entity'
                alias: User
            Task:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Todos/Task/Entity'
                prefix: 'App\Domain\Todos\Task\Entity'
                alias: Task
